/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Estudiantes
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private final Modelo modelo;
    private Controlador control;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(Modelo aThis) {
        modelo = aThis;
        initComponents();
        capturarEventos();
    }

    public Modelo getModelo() {
        return modelo;
    }

    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public JLabel getLblResultado() {
        return lblResultado;
    }

    public JTextField getTxtNumero() {
        return txtNumero;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Ingrese un número");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 110, 20);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(150, 30, 60, 30);

        btnCalcular.setText("Calcular");
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(40, 73, 170, 40);

        lblResultado.setText("Fibonacci es: ");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(40, 140, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos() {
        btnCalcular.addActionListener(getControl());
    }
}
